openapi: 3.0.3
info:
  title: pagos_movil
  version: 0.1.0

tags:
  - name: demo
    description: Endpoints de demo

paths:
  /health:
    get:
      tags: [demo]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
